
// Automatically generated by 'sgv prebuild' 1.0.0-alpha.2.
using System;
using System.Reflection;

[assembly: AssemblyVersion(@"1.0")]
[assembly: AssemblyFileVersion(@"0.18626.44847.52114")]
[assembly: AssemblyInformationalVersion(@"1.0.0-a02 Sha:e308307ef7371ff27586f9cac58d7e2eb70de1ef User:CEDRIC-LAPTOP\cedri_000")]

[assembly: SimpleGitVersionInfo( "1.0.0-alpha.2", "2016-01-13 09:40:43Z", "0.12.1" )]

/// <summary>
/// Automatically generated by 'sgv prebuild' 1.0.0-alpha.2. 
/// </summary>
class SimpleGitVersionInfoAttribute : Attribute
{
    public SimpleGitVersionInfoAttribute( string semVer, string buildTimeUtc, string sgvVersion )
    {
        SemVer = semVer;
        BuildTimeUtc = buildTimeUtc;
        SGVVersion = sgvVersion;
    }

    public readonly string SemVer;
    public readonly string BuildTimeUtc;
    public readonly string SGVVersion;
    
    public override string ToString()
    {
        return String.Format( "SemVer: {0}, BuildTimeUtc: {1}, SGVVersion: {2}", SemVer, BuildTimeUtc, SGVVersion );
    }
}
