version: build{build}
image: Visual Studio 2022
clone_folder: C:\CKli-World\CK-Crs-Projects\CK-Crs
environment:
  CODECAKEBUILDER_SECRET_KEY:
    secure: 8VAzdXgUQaJyFoU3WLf2iPFV/8zPDm9qV4TfOpx8/rg=
test: false
on_finish:
- ps: "'Get-ChildItem -Recurse *.log -exclude LastRun.log | % { Push-AppveyorArtifact $_.FullName }'"
install:
- ps: Install-Product node 16 x64
build_script:
- dotnet run --project CodeCakeBuilder -nointeraction
