using Cake.Common.IO;
using Cake.Npm;
using Cake.Npm.Pack;
using CK.Text;
using CodeCake.Abstractions;
using CSemVer;
using Newtonsoft.Json.Linq;
using System;
using System.IO;

namespace CodeCake
{
    public class NPMPublishedProject : NPMProject, ILocalArtifact
    {
        NPMPublishedProject(StandardGlobalInfo globalInfo, NormalizedPath path, SimplePackageJsonFile json, SVersion v )
            : base( globalInfo, path, json )
        {
            ArtifactInstance = new ArtifactInstance( new Artifact( "NPM", json.Name ), globalInfo.Version );
            string tgz = json.Name.Replace( "@", "" ).Replace( '/', '-' );
            TGZName = tgz + "-" + v.ToString() + ".tgz";
        }

        public override bool IsPublished => true;

        public ArtifactInstance ArtifactInstance { get; }

        public string Name => ArtifactInstance.Artifact.Name;

        public string TGZName { get; }

        private protected override void DoRunScript( string n )
        {
            using( TemporarySetVersion( ArtifactInstance.Version ) )
            {
                base.DoRunScript( n );
            }
        }

        /// <summary>
        /// Generates the .tgz file in the <see cref="StandardGlobalInfo.ReleasesFolder"/>
        /// by calling npm pack.
        /// </summary>
        /// <param name="globalInfo">The global information object.</param>
        /// <param name="cleanupPackageJson">
        /// By default, "scripts" and "devDependencies" are removed from the package.json file.
        /// </param>
        /// <param name="packageJsonPreProcessor">Optional package.json pre processor.</param>
        public void RunPack( Action<JObject> packageJsonPreProcessor = null )
        {
            using( TemporaryPrePack( ArtifactInstance.Version, packageJsonPreProcessor ) )
            {
                GlobalInfo.Cake.NpmPack( new NpmPackSettings()
                {
                    LogLevel = NpmLogLevel.Info,
                    WorkingDirectory = DirectoryPath.Path
                } );
            }
            var tgz = DirectoryPath.AppendPart( TGZName );
            if( !File.Exists( tgz ) )
            {
                GlobalInfo.Cake.TerminateWithError( $"Package file '{tgz}' has not been generated by 'npm pack'." );
            }
            var target = GlobalInfo.ReleasesFolder.AppendPart( TGZName );
            GlobalInfo.Cake.CopyFile( tgz.Path, target.Path );
            GlobalInfo.Cake.DeleteFile( tgz.Path );
        }

        public static NPMPublishedProject Load(StandardGlobalInfo globalInfo, NormalizedPath directoryPath, string expectedName = null, SVersion v = null )
        {
            var json = new SimplePackageJsonFile( directoryPath );
            if( expectedName != null && json.Name != expectedName )
            {
                throw new Exception( $"NPM package '{directoryPath}' must be a published package named '{expectedName}', not '{json.Name}'." );
            }
            if( v == null ) v = SVersion.TryParse( json.Version );
            return new NPMPublishedProject( globalInfo, directoryPath, json, v );
        }

    }
}
